Repository primefaces/primevue, pull requests merged in 2022-11, with the labels that each got.

#3230 Workflow Label changes
  .github/workflows/issue-inactive-checker.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/pr-checker.yml
Labels: Core Team, github_actions

#3252 Slider : fix undefined modelValue in slider
  src/components/slider/Slider.vue
Labels: vue2

#2981 Issue correction #2980
  src/components/inputnumber/InputNumber.vue
Labels: vue2, Status: In Progress

#3290 Sidebar: Header slot added
  api-generator/components/sidebar.js
  src/components/sidebar/Sidebar.d.ts
  src/components/sidebar/Sidebar.vue
  src/views/sidebar/SidebarDoc.vue
  src/views/slider/SliderDoc.vue
Labels: vue2

#2933 Password component default value display issue fixed
  src/components/password/Password.vue
Labels: Type: Bug, vue2
