Repository primefaces/primevue, pull requests merged in 2022-09, with the labels that each got.

#2934 Password meter dynamic changes problem solved
  src/components/password/Password.vue
Labels: need revision

#2927 Display control props added to carousel component
  api-generator/components/carousel.js
  src/components/carousel/Carousel.d.ts
  src/components/carousel/Carousel.vue
  src/views/carousel/CarouselDoc.vue
Labels: need revision

#2976 Breadcrumb accessibility improvment
  src/components/breadcrumb/Breadcrumb.vue
  src/components/breadcrumb/BreadcrumbItem.vue
  src/views/breadcrumb/BreadcrumbDoc.vue
Labels: pending-review, accessibility

#3027 Demo issue fixed
  src/views/steps/StepsDemo.vue
Labels: vue2

#2993 Tabmenu changes for accessibility
  src/components/tabmenu/TabMenu.vue
  src/views/tabmenu/TabMenuDoc.vue
Labels: pending-review, accessibility

#2999 Add custom icons support for Dropdown component
  api-generator/components/dropdown.js
  src/components/dropdown/Dropdown.d.ts
  src/components/dropdown/Dropdown.spec.js
  src/components/dropdown/Dropdown.vue
  src/views/dropdown/DropdownDoc.vue
Labels: need revision

#3001 Add custom icons support for CascadeSelect component
  api-generator/components/cascadeselect.js
  src/components/cascadeselect/CascadeSelect.d.ts
  src/components/cascadeselect/CascadeSelect.spec.js
  src/components/cascadeselect/CascadeSelect.vue
  src/components/cascadeselect/CascadeSelectSub.vue
  src/views/cascadeselect/CascadeSelectDoc.vue
Labels: need revision
