Repository primefaces/primevue, pull requests merged in 2022-06, with the labels that each got.

#1907 Add on error for images
  src/components/image/Image.vue
Labels: need revision

#2550 resolves #2481 added a method for clearing the filter input
  src/components/multiselect/MultiSelect.vue
  src/views/multiselect/MultiSelectDemo.vue
  src/views/multiselect/MultiSelectDoc.vue
Labels: need revision

#2599 Check which edit mode when calling editor save callback and editor cancel callback
  src/components/datatable/BodyCell.vue
Labels: discussion, pending-review

#2692 Accessibility for InputText
  src/views/inputtext/InputTextDoc.vue
Labels: accessibility

#2693 Accessibility for Textarea
  src/views/textarea/TextareaDoc.vue
Labels: accessibility

#2717 Accessibility for InputSwitch
  src/components/inputswitch/InputSwitch.vue
  src/views/inputswitch/InputSwitchDoc.vue
Labels: accessibility

#2718 Accessibility for Checkbox
  src/components/checkbox/Checkbox.vue
  src/views/checkbox/CheckboxDemo.vue
  src/views/checkbox/CheckboxDoc.vue
Labels: accessibility

#2719 Accessibility for RadioButton
  src/components/radiobutton/RadioButton.vue
  src/views/radiobutton/RadioButtonDemo.vue
  src/views/radiobutton/RadioButtonDoc.vue
Labels: accessibility

#2723 Accessibility for Button
  src/components/button/Button.vue
  src/components/ripple/Ripple.js
  src/views/button/ButtonDemo.vue
  src/views/button/ButtonDoc.vue
Labels: accessibility

#2722 Accessibility for Password
  api-generator/components/password.js
  src/components/password/Password.d.ts
  src/components/password/Password.vue
  src/views/password/PasswordDoc.vue
Labels: accessibility

#2721 Accessibility for Slider
  api-generator/components/slider.js
  src/components/slider/Slider.d.ts
  src/components/slider/Slider.vue
  src/views/slider/SliderDoc.vue
Labels: pending-review, accessibility
