Repository primefaces/primevue, pull requests merged in 2023-10, with the labels that each got.

#4523 Fixed #4522 - Add extra check for separator item
  components/lib/panelmenu/PanelMenuList.vue
Labels: Resolution: Needs Revision

#2942 TreeTable: Slot for custom column header in 2.x
  src/components/treetable/HeaderCell.vue
  src/views/treetable/TreeTableTemplatingDemo.vue
Labels: vue2

#4526 Add resize event to splitter
  components/lib/splitter/Splitter.d.ts
  components/lib/splitter/Splitter.vue
  doc/common/apidoc/index.json
Labels: Resolution: Needs Revision, Resolution: Needs Issue

#4525 Fix TailwindCSS theme for splitter component
  components/lib/passthrough/tailwind/index.js
Labels: Resolution: Needs Issue

#4520 Add missing order to buttons and input on InputNumber if buttonLayout…
  components/lib/passthrough/tailwind/index.js
Labels: Resolution: Needs Issue
