Repository primefaces/primevue, pull requests merged in 2023-09, with the labels that each got.

#3866 AutoComplete: show overlay if there are no suggestions
  components/lib/autocomplete/AutoComplete.spec.js
  components/lib/autocomplete/AutoComplete.vue
Labels: Status: Pending Review

#4114 Fix #4113: Calendar showMonthAfterYear locale option
  components/lib/calendar/Calendar.vue
  components/lib/config/PrimeVue.d.ts
  components/lib/config/PrimeVue.js
Labels: Status: Pending Review

#3520 ColumnFilter: Add 'applyFilter' prop to filter template
  components/lib/datatable/ColumnFilter.vue
Labels: Resolution: Needs Revision

#4457 Fix: Sidebar Docs missing quotes
  doc/sidebar/pt/PTDoc.vue
Labels: Component: Documentation

#4464 Textarea autoResize issue
  components/lib/textarea/Textarea.vue
Labels: Resolution: Needs Revision
