Repository primefaces/primevue, pull requests merged in 2024-01, with the labels that each got.

#5037 Fix typo in bulma documentation
  pages/bulma/index.vue
Labels: Component: Documentation

#5039 Fixed #5038 - v2 Menu | disabled property as a function is not worki…
  src/components/menu/Menu.vue
Labels: vue2

#4747 fix(input-number): when zero is entered, value displayed isn't expected
  components/lib/inputnumber/InputNumber.vue
Labels: Resolution: Needs Revision

#5128 Icon id hydration
  components/lib/baseicon/BaseIcon.vue
  components/lib/icons/arrowdown/index.vue
  components/lib/icons/arrowup/index.vue
  components/lib/icons/ban/index.vue
  components/lib/icons/exclamationtriangle/index.vue
  components/lib/icons/eyeslash/index.vue
  components/lib/icons/filter/index.vue
  components/lib/icons/filterslash/index.vue
  components/lib/icons/infocircle/index.vue
  components/lib/icons/pencil/index.vue
  components/lib/icons/plus/index.vue
  components/lib/icons/refresh/index.vue
  components/lib/icons/search/index.vue
  components/lib/icons/searchminus/index.vue
  components/lib/icons/searchplus/index.vue
  components/lib/icons/sortalt/index.vue
  components/lib/icons/sortamountdown/index.vue
  components/lib/icons/sortamountupalt/index.vue
  components/lib/icons/spinner/index.vue
  components/lib/icons/star/index.vue
  components/lib/icons/starfill/index.vue
  components/lib/icons/thlarge/index.vue
  components/lib/icons/timescircle/index.vue
  components/lib/icons/trash/index.vue
  components/lib/icons/undo/index.vue
  components/lib/icons/upload/index.vue
  components/lib/icons/windowmaximize/index.vue
  components/lib/icons/windowminimize/index.vue
Labels: Resolution: Needs Revision
