Repository primefaces/primevue, pull requests merged in 2025-09, with the labels that each got.

#8071 fix style of checkbox icon when disabled (volt)
  apps/volt/volt/Checkbox.vue
Labels: Type: Enhancement

#8120 feat(drawer): add closeOnEscape prop to control closing on Escape Key
  apps/showcase/doc/common/apidoc/index.json
  packages/primevue/src/drawer/BaseDrawer.vue
  packages/primevue/src/drawer/Drawer.d.ts
  packages/primevue/src/drawer/Drawer.vue
Labels: Type: New Feature

#8136 Add collapsed to panel header slot
  packages/primevue/src/panel/Panel.d.ts
  packages/primevue/src/panel/Panel.vue
Labels: Type: Enhancement

#8133 fix(ConfirmDialog): add drag functionality to container template
  packages/primevue/src/confirmdialog/ConfirmDialog.d.ts
  packages/primevue/src/confirmdialog/ConfirmDialog.vue
Labels: Resolution: Needs Revision
