Repository primefaces/primevue, pull requests merged in 2025-01, with the labels that each got.

#7038 correct field type for column body slot
  packages/primevue/src/column/Column.d.ts
Labels: Type: Bug

#6844 Implements "pause on hover" Toast feature & exposes onMouseEnter and onMouseLeave callback props
  packages/primevue/src/toast/BaseToast.vue
  packages/primevue/src/toast/Toast.d.ts
  packages/primevue/src/toast/ToastMessage.vue
Labels: Type: Enhancement

#7044 fix: InputNumber unexpected behavior when using allow-empty attribute…
  packages/primevue/src/inputnumber/InputNumber.vue
Labels: Status: Pending Review, Resolution: Needs Revision

#7131 fix(floatlabel): correct font.weight style key weight for active label
  packages/primevue/src/floatlabel/style/FloatLabelStyle.js
Labels: Resolution: Needs Revision
