Repository primefaces/primevue, pull requests merged in 2025-03, with the labels that each got.

#7427 Infer the DataTable generic type from the value prop
  packages/core/src/index.d.ts
  packages/primevue/src/datatable/DataTable.d.ts
Labels: Status: Pending Review

#7170 Fixed issue in Select.vue
  packages/primevue/src/select/Select.vue
Labels: Status: Pending Review

#7353 fix: add resize observer on VirtualScroller component
  packages/primevue/src/virtualscroller/VirtualScroller.vue
Labels: Type: Enhancement

#7287 fix(form): make FormSubmitEvent generic for better type safety
  packages/forms/src/form/Form.d.ts
Labels: Resolution: Needs Issue

#7160 fix: DatePicker/Select fix outsideClickListener inside web components
  packages/primevue/src/datepicker/DatePicker.vue
  packages/primevue/src/select/Select.vue
Labels: Status: Pending Review

#7063 fix(InputNumber): added "required" prop which is present in wrapped component (InputText) already
  packages/primevue/src/inputnumber/BaseInputNumber.vue
  packages/primevue/src/inputnumber/InputNumber.vue
Labels: Type: Enhancement

#6454 fix: add an extra condition for tryOnMounted method
  packages/core/src/usestyle/UseStyle.js
Labels: Resolution: Help Wanted
